name: mimoapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.0
  curved_navigation_bar: ^1.0.3 
  bottom_navy_bar: ^6.0.0

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  http: ^1.1.0
  bottom_nav_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/begin_image/
    - assets/images/plash_image/
    - assets/images/signin-signup_image/

  fonts:
    - family: Caprasimo
      fonts:
        - asset: assets/fonts/Caprasimo-Regular.ttf
          style: italic
